# Generated by Django 2.0.1 on 2018-01-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={'ordering': ('modified_on',), 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AddField(
            model_name='recipes',
            name='published_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default=('Draft', 'Draft'), max_length=50),
        ),
    ]
